site_name: MiniMind-V
site_description: MiniMind-V - 超小多模态视觉语言模型 / Super-Small Multimodal Vision-Language Model
site_author: jingyaogong
site_url: https://minimind-v.readthedocs.io/

# 搜索插件配置
plugins:
  - search:
      lang: en

# 主题配置
theme:
  name: material
  favicon: images/logo.png
  icon:
    logo: material/book-open-page-variant
  palette:
    # 浅色模式
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式
  features:
    # - navigation.instant    # 与多语言切换不兼容，已禁用
    - navigation.tracking     # 锚点跟踪
    - navigation.sections     # 导航分组
    - navigation.expand       # 默认展开导航
    - navigation.top          # 返回顶部按钮
    - search.suggest          # 搜索建议
    - search.highlight        # 搜索高亮
    - content.code.copy       # 代码复制按钮
    - toc.follow              # 目录跟随
    - toc.integrate           # 目录集成到左侧边栏
  language: en

# 导航结构
nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Model Training: training.md

# Markdown 扩展
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

